Feature/pap 39
YandexPracticum-C27-T03/yandex-praktikum-module-2 pull request #17
Opened 2023-07-19 22:22 UTC by Dveyn

Добавить Service Workers
Приложение должно попадать в кеш при первой загрузке и после этого загружаться без интернета — не только элементы входа и пользовательские настройки, но и сама игра. Допускается использование плагинов для создания конфигурации воркера, но сам функционал требуется написать самостоятельно в соответствии с материалами из уроков.

2023-07-20 16:49 UTC, Olegas requested changes
Добрый день.
Есть вопрос к реализации.
Есть ли где-то гарантия, что вы успеете отправить message в SW ДО тех пор, пока случится событие install? Где сказано, что промис, который вернет register сработает ДО ТОГО как случится событие install внутри SW?
Потому что если не успеете, вы в кэш никогда ничего не добавите.

2023-07-21 10:44 UTC, Olegas commented on packages/client/public/service-worker.js
> +  return cashedRequest || networkFirst(request);
А в чем разница между этими двумя ветками? Тут же одно и тоже внутри написано

2023-07-21 10:45 UTC, Olegas commented on packages/client/public/service-worker.js
> +  cache.addAll(staticAssets);
Думаю тут нужно не забыть сделать **event.waitUntil** чтобы перед тем как активировать дождаться что все закэшируется.

2023-07-21 10:47 UTC, Olegas approved these changes
Проблема с инициализацией решена, все ок.
Написал еще пару мелких замечаний которые лучше исправить.
Но в целом работу могу принять.

2023-07-29 00:48 UTC, N1KN approved these changes

2023-07-29 20:28 UTC, Dveyn commented
Service Workers

2023-07-29 20:28 UTC, merged