[feature/pap-41] remove fullscreen button
YandexPracticum-C27-T03/yandex-praktikum-module-2 pull request #19
Opened 2023-07-20 06:54 UTC by YuryXVX

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-21 19:17 UTC, 40thz submitted a review, later dismissed

2023-07-21 19:57 UTC, IvanPeleshok commented on packages/client/src/entities/game/ui/game-header/ui/game-header.tsx
> +export const GameHeader = ({ children }: GameHeaderProps) => {
Советую использовать дженерик тип PropsWithChildren
```
export const GameHeader: FC<PropsWithChildren<Props>> = (props) => {
```
https://blog.logrocket.com/using-react-children-prop-with-typescript/#using-propswithchildren-type:~:text=In%20practice%2C%20here%E2%80%99s%20the%20definition%20for%20the%20PropsWithChildren%20type%3A

2023-07-21 19:59 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/useFullscreen.ts
> +import { fscren } from '@@shared/lib/fullscreen';
Могу ошибаться, но не хватает scre`E`n

2023-07-21 20:00 UTC, IvanPeleshok commented on packages/client/src/shared/hooks/useFullscreen.ts
> +      return fscren.exitFullscreen().then(() => {
Не используем callback-и
Предлагаю переписать на async / await + try / catch
https://learn.javascript.ru/async-await

2023-07-21 20:02 UTC, IvanPeleshok commented on packages/client/src/shared/ui/Fullscreen/FullscreenContainer.tsx
> +    <div ref={handle.root} style={handle.active ? { height: '100%', width: '100%' } : undefined}>
Точно необходимы инлайновые стили?
Может всё-таки через классы изменить стилистику?

2023-07-21 20:03 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-21 22:16 UTC, N1KN approved these changes, later dismissed

2023-07-23 12:51 UTC, IvanPeleshok approved these changes

2023-07-27 07:36 UTC, 40thz approved these changes

2023-07-27 07:38 UTC, merged