Feature/pap 13
YandexPracticum-C27-T03/yandex-praktikum-module-2 pull request #2
Opened 2023-06-30 14:08 UTC by YuryXVX

1. Добавил роутер
2. Изменил структуру проект под fsd

2023-06-30 14:42 UTC, 40thz submitted a review, later dismissed
ok

2023-06-30 18:48 UTC, Dveyn approved these changes, later dismissed

2023-06-30 19:00 UTC, 40thz approved these changes, later dismissed

2023-07-01 22:37 UTC, N1KN requested changes
Поправь, пожалуйста нейминг файлов;
Верни вспомогательные функции makeMapState, useMapState, ..., либо приглашаю к обсуждению.

Ну и там пара вопросов: можешь либо ответить, либо просто пометить решенным, если не хочешь отвечать. Они чисто ради любопытства.

2023-07-01 22:37 UTC, N1KN commented on packages/client/src/app/appEntry.tsx
> +      <Provider store={appStore}>
Для однобразности я бы `appStore` тоже функцией сделал или `appRouter` константой.

2023-07-01 22:37 UTC, N1KN commented on packages/client/src/shared/lib/model/hooks.ts
> +export const useAppDispatch = useDispatch<AppDispatch>;
Считаю, что мой вариант с makeMapState и makeMapDispatch был лучше. Он чище при множественном использовании селекторов, плюс в местах использования экшнов не нужно прокидывать dispatch.
 
Конкретно тут излишне(т.к. всего один селектор и экшн), но для примера лучше оставить его использование и тут.

2023-07-01 22:37 UTC, N1KN commented on packages/client/src/pages/main/ui/Page.tsx
> +  const dispatch = useAppDispatch();
Описал в коментарии к `@@shared/lib/model/hooks` на счёт возвращения изначальных хуков для работы с redux.

2023-07-01 22:37 UTC, N1KN commented on packages/client/types/common.d.ts
> +declare global {
Я думал, что эти TS утилиты должны быть в shared.. Разве нет?

*Это вопрос, если что, не часть ревью.*

2023-07-01 22:37 UTC, N1KN commented on packages/client/src/entities/theme/model/selectors.ts
> +export const selectCurrentTheme = (state: RootState) => selectThemeModule(state).theme;
```
export const selectCurrentTheme = (state: RootState) => selectThemeModule(state).theme;
```

Имхо createSelector выгдядит красивее, т.к. виден "поток данных" и мы используем аргумент, а не результат выполнения функции через точку(это немного не очевидно при чтении кода).

Лучше писать результат в переменную.
Либо как я через createSelector, либо хотя бы так:
```suggestion
export const selectCurrentTheme = (state: RootState) => {
    const themeState = selectThemeModule(state);
    return themeState.theme;
 };
```

2023-07-01 22:37 UTC, N1KN commented on packages/client/src/hooks/useTheme.ts
Почему избавился от этого хука?

Вижу что перенес функционал в стор, просто интересно.

2023-07-01 22:37 UTC, N1KN commented on packages/client/src/entities/theme/model/slice.ts
В целом, согласен, со слайсами тоже не плохо выглядит :)

2023-07-01 22:37 UTC, N1KN commented on packages/client/src/app/appEntry.tsx
Давай придерживаться `kebab-case` в именовании файлов, а `camelCase` оставим переменным.

2023-07-03 14:01 UTC, YuryXVX commented on packages/client/src/app/appEntry.tsx
поправил

2023-07-03 14:02 UTC, YuryXVX commented on packages/client/src/pages/main/ui/Page.tsx
> +  const dispatch = useAppDispatch();
готово

2023-07-03 14:02 UTC, YuryXVX commented on packages/client/src/shared/lib/model/hooks.ts
> +export const useAppDispatch = useDispatch<AppDispatch>;
вернул

2023-07-03 14:06 UTC, 40thz approved these changes, later dismissed

2023-07-03 14:23 UTC, N1KN submitted a review, later dismissed

2023-07-03 14:48 UTC, N1KN approved these changes

2023-07-03 14:51 UTC, merged