feat: Решил задачу PAP-38;
YandexPracticum-C27-T03/yandex-praktikum-module-2 pull request #23
Opened 2023-07-23 19:33 UTC by N1KN

Добавлены текстуры препятствий, фона и игрока; Реализован загрузчик ресурсов; Реализована анимация движения фона(бесконечный фон); Реализована анимация бега персонажа; Добавлена сущность движка SpriteEntity с возможностью вывода изображений, а в сущность Player внесены изменения позволяющие выводить анимацию; Так-же выполнен рефакторинг game-preview, т.к. некоторые элементы работали некоректно из-за перерендеров(заменил переменные на рефы)

### Какую задачу решаем
[PAP-38](https://linear.app/papprika/issue/PAP-38/)

### Скриншоты/видяшка (если есть)
![image](https://github.com/YandexPracticum-C27-T03/yandex-praktikum-module-2/assets/37019408/4ed7e8ce-83c0-49c7-9cfe-6ddb086fe182)
![image](https://github.com/YandexPracticum-C27-T03/yandex-praktikum-module-2/assets/37019408/489fd725-f96d-4472-8707-ca9fe001a552)

2023-07-23 20:43 UTC, YuryXVX approved these changes, later dismissed

2023-07-24 06:17 UTC, IvanPeleshok commented on packages/client/src/entities/game/lib/utils/resource-loader.ts
> +      .then(() => {
Предлагаю перейти на async / await + try / catch
https://learn.javascript.ru/async-await

2023-07-24 06:22 UTC, IvanPeleshok commented on packages/client/src/pages/game/ui/Page.tsx
> +    return () => void resourceLoader.off(ResourceLoaderEvents.Success, onLoad);
Впервые вижу запись, чтобы возвращался void
Точно так и планировалось?
Недостаточно вернуть следующее?
```
return () => resourceLoader.off(ResourceLoaderEvents.Success, onLoad)
```

2023-07-24 06:23 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-24 09:32 UTC, N1KN commented on packages/client/src/entities/game/lib/utils/resource-loader.ts
> +      .then(() => {
А как? Тут-же как раз смысл в том, что нужно выяснить какой промис раньше выполниться(.race) и чтобы все промисы были успешны(.all)

Мне кажется тут более чисто будет использовать именно Promise., а не сахар в виде ассинхронных функций.

Или имеется в виду, что за место .then на 29ой строке?

2023-07-24 09:33 UTC, N1KN commented on packages/client/src/entities/game/lib/utils/resource-loader.ts
> +      .then(() => {
> Предлагаю перейти на async / await + try / catch https://learn.javascript.ru/async-await

А как? Тут-же как раз смысл в том, что нужно выяснить какой промис раньше выполниться(.race) и чтобы все промисы были успешны(.all)

Мне кажется тут более чисто будет использовать именно Promise., а не сахар в виде ассинхронных функций.

Или имеется в виду, что за место .then на 29ой строке?

2023-07-24 09:52 UTC, IvanPeleshok commented on packages/client/src/entities/game/lib/utils/resource-loader.ts
> +      .then(() => {
Да, заменить колбеки then / catch на async / await + try / catch

2023-07-24 13:45 UTC, N1KN commented on packages/client/src/pages/game/ui/Page.tsx
> +    return () => void resourceLoader.off(ResourceLoaderEvents.Success, onLoad);
Отметил комментарием. Это обход ошибки типа данных: TS2345
![image](https://github.com/YandexPracticum-C27-T03/yandex-praktikum-module-2/assets/37019408/dbc3a205-ab70-410a-a17a-bcc84d69d080)

2023-07-24 13:49 UTC, 40thz approved these changes

2023-07-24 14:43 UTC, IvanPeleshok commented on packages/client/src/pages/game/ui/Page.tsx
> +    return () => void resourceLoader.off(ResourceLoaderEvents.Success, onLoad);
Можно было так поступить:
```
() => {
   fn()
 }
```

2023-07-24 14:43 UTC, IvanPeleshok approved these changes

2023-07-24 15:37 UTC, N1KN commented on packages/client/src/pages/game/ui/Page.tsx
> +    return () => void resourceLoader.off(ResourceLoaderEvents.Success, onLoad);
> Можно было так поступить:
> 
> ```
> () => {
>    fn()
> }
> ```

Согласен, можно, но мне кажется так чище выглядит. Спасибо за совет :)

2023-07-24 15:39 UTC, merged