Create notification
YandexPracticum-C27-T03/yandex-praktikum-module-2 pull request #26
Opened 2023-08-08 20:04 UTC by Dveyn

Добавил работу с notification
Добавил внутреннее уведомления

2023-08-09 07:05 UTC, N1KN requested changes

2023-08-09 07:05 UTC, N1KN commented on packages/client/src/entities/game/ui/game-view.tsx
> +    if (gameStatus === GAME_STATUS.RESTART) {
При старте уровня заново уведомление, либо пропадать должно, либо нужно как-то зафиксировать его значения, иначе у нас получается так, что в уведомлении счёт меняется по ходу игры.

2023-08-09 07:27 UTC, N1KN commented on packages/client/src/features/notifications/ui/notification.tsx
> +const Notification: React.FC<NotificationProps> = ({ title, message }) => {
Уведомления не со стэком должны быть?
У нас по идее это должно и при авторизации использоваться уведомления для всего приложения, а не для конкретной задачи

2023-08-14 08:55 UTC, YuryXVX approved these changes, later dismissed

2023-08-14 18:58 UTC, IvanPeleshok approved these changes
Замечательная работа, апрув

2023-08-15 13:32 UTC, N1KN submitted a review, later dismissed

2023-08-16 06:30 UTC, N1KN approved these changes, later dismissed

2023-08-16 06:31 UTC, N1KN commented on packages/client/src/entities/game/ui/game-view.tsx
>    }, [gameStatus, record, score]);
Если отключаешь правила eslint, то пиши почему ты это сделал, по правь и вливаем

2023-08-16 07:06 UTC, N1KN approved these changes

2023-08-16 07:06 UTC, merged