[feature/PAP-55] add emoji picker
YandexPracticum-C27-T03/yandex-praktikum-module-2 pull request #31
Opened 2023-08-19 13:33 UTC by YuryXVX

Добавил emoji-picker и возможность оставить реакцию на топик форума.

2023-08-19 14:38 UTC, NikitaFilippovAleks requested changes

2023-08-19 14:38 UTC, NikitaFilippovAleks commented on packages/client/src/pages/forum/ui/SingleTopic/single-topic.tsx
> +  // qwerty123
для чего эти комменты?

2023-08-19 14:38 UTC, NikitaFilippovAleks commented on packages/client/src/shared/ui/EmojiPicker/components/Tab/styles.scss
> +  background-image: url("data:image/svg+xml,%3C%3Fxml version='1.0' encoding='utf-8'%3F%3E%3C!-- Generator: Adobe Illustrator 26.3.1, SVG Export Plug-In . SVG Version: 6.00 Build 0) --%3E%3Csvg versi
может svg в отдельный файл ввынести?

2023-08-19 15:06 UTC, YuryXVX commented on packages/client/src/shared/ui/EmojiPicker/components/Tab/styles.scss
> +  background-image: url("data:image/svg+xml,%3C%3Fxml version='1.0' encoding='utf-8'%3F%3E%3C!-- Generator: Adobe Illustrator 26.3.1, SVG Export Plug-In . SVG Version: 6.00 Build 0) --%3E%3Csvg versi
Готово.

2023-08-19 15:06 UTC, YuryXVX commented on packages/client/src/pages/forum/ui/SingleTopic/single-topic.tsx
> +  // qwerty123
Убрал.

2023-08-19 15:07 UTC, NikitaFilippovAleks submitted a review, later dismissed

2023-08-19 17:28 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду.
Оставил комментарии.

2023-08-19 17:28 UTC, Olegas commented on packages/client/src/pages/forum/ui/ReactionsTopic/lib/reaction-adapter.ts
> +      count: acc[reaction] || 0 ? (acc[reaction].count += 1) : 1,
|| 0 тут явно лишнее. И += 1 можно смело заменить на просто + 1

2023-08-19 17:28 UTC, Olegas commented on packages/client/src/shared/ui/EmojiPicker/hooks/useActiveTypeTab.ts
> +      observer = null;
Нужно observer сделать disconnect()

2023-08-19 17:28 UTC, Olegas commented on packages/client/src/shared/ui/EmojiPicker/utils/dom-utils/scroll-to.ts
> +  });
А вот это API вам не поможет: https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView ?

2023-08-20 10:01 UTC, YuryXVX commented on packages/client/src/pages/forum/ui/ReactionsTopic/lib/reaction-adapter.ts
> +      count: acc[reaction] || 0 ? (acc[reaction].count += 1) : 1,
Поправил

2023-08-20 10:01 UTC, YuryXVX commented on packages/client/src/shared/ui/EmojiPicker/utils/dom-utils/scroll-to.ts
> +  });
Решил использовать чутка другое апи scrollTo()

2023-08-20 12:27 UTC, Olegas approved these changes
Работа принята, спасибо.

2023-08-24 14:23 UTC, NikitaFilippovAleks approved these changes, later dismissed

2023-08-25 08:29 UTC, Dveyn approved these changes

2023-08-25 08:55 UTC, merged