Добавил API авторизации/регистрации, подключил к стору
YandexPracticum-C27-T03/yandex-praktikum-module-2 pull request #5
Opened 2023-07-05 16:55 UTC by 40thz

### Какую задачу решаем
- Сверстана страница авторизации. 

- Добавлен роут для страницы авторизации. 

- Подключить[ API Практикума](https://ya-praktikum.tech/api/v2/swagger/#/Auth/post_auth_signin) для авторизации пользователя.

- Добавить слайс для юзера (к примеру).

- После авторизации класть информацию о юзере в слайс.

- Фикс ошибки связанную с ref в компоненте формы

- Добавил проверку авторизации

### Скриншоты/видяшка (если есть)
нет

### TBD (если есть)
нет

2023-07-05 18:39 UTC, N1KN requested changes
Поправь эти моменты(что не нужно править - я отдельно указываю)

2023-07-05 18:39 UTC, N1KN commented on packages/client/src/shared/lib/hooks/useAuth.ts
> +  const mapState = makeMapState((state) => ({
makeMapState должен быть за пределами хука/компонента

2023-07-05 18:39 UTC, N1KN commented on packages/client/src/entities/user/index.ts
> +export { getCurrentUser } from './model/selectors';
Нужно добавить экспорт слайса.

```suggestion
export { getCurrentUser } from './model/selectors';
export { userSlice } from './model/slice';

```

2023-07-05 18:39 UTC, N1KN commented on packages/client/src/entities/user/model/reducers.ts
> +import authService from '@@entities/user/api/auth.service';
Не используй экспорт по умолчанию и укажи то, что нужно экспортировать в `src/entities/user/index.ts`

2023-07-05 18:39 UTC, N1KN commented on packages/client/src/pages/main/__tests__/page.test.tsx
> +import { userSlice } from '@@entities/user/model/slice';
Здесь, по идее, тоже не корректно..

2023-07-05 18:39 UTC, N1KN commented on packages/client/src/entities/user/model/slice.ts
> +      return { ...state, isLoading: true };
> Это просто к сведению, не обязательно сейчас исправлять

По скольку мы используем @reduxjs/toolkit, необязательно возвращать состояние из редьюсера, можно менять его через точку.

2023-07-05 18:39 UTC, N1KN commented on packages/client/src/app/auth-provider.tsx
Как будто бы Provider это что-то связанное с React.Context... 
Мне кажется этот код должен быть где-то в другом месте..

2023-07-05 18:39 UTC, N1KN commented on packages/client/src/shared/lib/hooks/useAuth.ts
> +  const { isLoading, isAuth, data } = user;
Можно декомпозировать чуть глубже
```suggestion
    const {
    user: { isLoading, isAuth, data },
  } = useMapState(mapState);
```

2023-07-05 18:39 UTC, N1KN commented on packages/client/src/shared/lib/http/index.ts
> +export { http };
Можно сразу так:

```suggestion
export { http } from './http';
```

2023-07-05 18:39 UTC, N1KN commented on packages/client/src/shared/ui/Form/Form.tsx
> +  const RefInput = forwardRef<HTMLInputElement, InputProps>((props, ref) => {
Мне кажется это должно быть в отдельном файле, т.к. это **компонент** хоть тут и просто проброс рефов.

Либо, хотя-бы вынеси за пределы рендер функции его.

2023-07-06 17:49 UTC, N1KN reviewed
Нарушение направленности импортов между слоями
И, возможно, нейминг.

А тае всё круто 😉

2023-07-06 17:49 UTC, N1KN commented on packages/client/src/pages/registration/ui/Page.tsx
> +import { AuthLayout } from '@@app/layouts/AuthLayout';
Нарушение FSD

2023-07-06 17:49 UTC, N1KN commented on packages/client/src/pages/login/ui/Page.tsx
> +import { AuthLayout } from '@@app/layouts/AuthLayout';
Нарушение FSD

2023-07-06 17:49 UTC, N1KN commented on packages/client/src/pages/login/ui/Page.tsx
> Можешь сейчас поправить, а можешь потом

Нейминг фацлов должен соответствовать kebab-case, я вроде указывал в доке.

Ещё, как поправишь просто зарезолвь эти коментарии

2023-07-06 17:50 UTC, N1KN approved these changes

2023-07-06 17:52 UTC, N1KN commented on packages/client/src/pages/login/ui/Page.tsx
Ечли нет кнопки "Resolve Conversation", отпиши в ЛС

2023-07-06 18:33 UTC, merged

2023-07-08 11:15 UTC, Olegas reviewed
Есть вопросы по коду, нужно исправить или объяснить, зачем так сделано.

2023-07-08 11:15 UTC, Olegas commented on packages/client/src/app/app-store.ts
> +        serializableCheck: false,
А для чего отключили эту опцию? Какие данные в сторе не прошли проверку на сериализацию?

2023-07-08 11:15 UTC, Olegas commented on packages/client/src/shared/lib/http/http.ts
> +export abstract class http {
Класс обычно называют с большой буквы.

2023-07-08 11:15 UTC, Olegas commented on packages/client/src/pages/login/ui/Page.tsx
> +  const onSubmit = async (data: UserLogin) => login(data);
А для чего тут async?

2023-07-08 11:15 UTC, Olegas commented on packages/client/src/pages/registration/ui/Page.tsx
> +  const onSubmit = async (data: UserRegistration) => registration(data);
Еще один странный async

2023-07-08 11:15 UTC, Olegas commented on packages/client/src/shared/lib/hooks/useAuth.ts
> +}));
Вот эти утилиты useMapState, useMapDispatch - они зачем?
Выглядят каким-то усложнением а пользы вроде как не видно.
Вот useMapState - это же просто useSelector. Но что бы им воспользоваться надо вызвать выше makeMapState который просто вернет то что ему передали. В чем идея? Почему просто не использовать useDispatch и useSelector напрямую?

2023-07-08 12:01 UTC, N1KN commented on packages/client/src/shared/lib/hooks/useAuth.ts
> +}));
https://github.com/YandexPracticum-C27-T03/yandex-praktikum-module-2/pull/2#discussion_r1248988200