feat: Добавил страницы ошибок 404 и 500 и немного поправил структуру
YandexPracticum-C27-T03/yandex-praktikum-module-2 pull request #7
Opened 2023-07-08 00:44 UTC by N1KN

Поправил вёрстку в AuthLayout и перенёс его в виджеты.

Прокинул box-sizing по всем компонентам, на всякий случай)

Добавил 404 и 500 страницы ошибок и докинул их в роутер

### Какую задачу решаем
[PAP-15](https://linear.app/papprika/issue/PAP-15)

2023-07-08 10:46 UTC, 40thz submitted a review, later dismissed
Есть момент связанный с неймингом, а так все ок)

2023-07-08 10:46 UTC, 40thz commented on packages/client/src/widgets/auth-layout/auth-layout.tsx
Т. к. этот компонент сейчас используется не только на странице с авторизацией/регистрацией, я бы назвал его как не будь по другому. Очень странно выглядит обертка "AuthLayout" на странице, которая никак не связанна с авторизацией.

2023-07-11 14:54 UTC, IvanPeleshok commented on packages/client/src/pages/not-found/ui/page.tsx
> +    window.history.back();
Вижу, что роутер в пакетах есть, но не подключён
Можно вынести в todo-шку :)

2023-07-11 14:56 UTC, IvanPeleshok commented on packages/client/src/widgets/auth-layout/auth-layout.tsx
> +export const AuthLayout = ({ children, title }: { children: React.ReactNode; title?: string }) => {
Предлагаю тип объявлять через interface
```
import { FC, PropsWithChildren } from 'react'

interface Props {
  title?: string
}

export const AuthLayout: FC<PropsWithChildren<Props>> = (props) => {}

```

2023-07-11 14:58 UTC, IvanPeleshok commented on packages/client/src/app/layers/auth-layer.tsx
> +export const AuthLayer = ({ children }: { children: React.ReactNode }) => {
Аналогично, переделать на интерфейс

2023-07-11 14:59 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-11 21:11 UTC, IvanPeleshok commented on packages/client/src/widgets/header-layout/header-layout.tsx
> +  children: React.ReactNode;
Для того, чтобы не объявлять children можно воспользоваться PropsWithChildren<T>
Очень удобно, всем советую :)
https://blog.logrocket.com/using-react-children-prop-with-typescript/#:~:text=types%20discussed%20below.-,Using%20the%20PropsWithChildren%20type,-The%20React.

2023-07-11 21:11 UTC, IvanPeleshok approved these changes

2023-07-12 07:21 UTC, YuryXVX approved these changes

2023-07-12 07:21 UTC, merged