[feature/pap-34] add profile feature
YandexPracticum-C27-T03/yandex-praktikum-module-2 pull request #9
Opened 2023-07-11 13:23 UTC by YuryXVX

- добавил фичи для изменения аватара/пароль
- добавил хуки для состояния запроса
- мелкий рефакторинг

2023-07-12 09:30 UTC, N1KN requested changes
Есть моменты, которые нужно поправить.

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/app/app-router.tsx
> +//test_yury@m.ru
Подписывай в комментарии что это тестовые данные для  входа

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/app/root-reducer.ts
> +  request: requestReducer,
Для преемственности тут либо requestSlice.reducer , либо все остальные редьюсеры аналогично использовать

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/shared/lib/model/request-helper-slice/selectors.ts
> +  // @ts-expect-error
Если отключаешь правило линтера или TS всегда обосновывай почему тут не будет ошибки о которой предупреждает TS, Linter и почему отключено правило.

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/shared/lib/model/request-helper-slice/slice.ts
> Объясни, пожалуйста, что тут должно быть, а то я чот туплю.

На будущее лучше коммент оставить зачем это, если оно НЕ явно используется/вызывается

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/entities/profile/ui/UserViewer.tsx
Мне кажется на всю страницу не стоит растягивать немного сложно читать, так гуд.

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/shared/lib/constants/common.ts
> +export const RESOURCES_ULR = 'https://ya-praktikum.tech/api/v2/resources';
Опечатка

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/entities/user/model/reducers.ts
> +    ...user,
Почему тут [userAdapter.ts](https://github.com/YandexPracticum-C27-T03/yandex-praktikum-module-2/pull/9/files#diff-62723c3ed53c63827028fc99f8688c1351ae5098c395d5a84781b6f6525a97e0) не использовал раз уж он написан?

Его либо удалить, либо использовать нужно.

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/features/profile-avatar/__tests__/ProfileAvatar.test.tsx
> +function noop() {}
Предлагаю, либо вынести эту функцию в хелперы shared, чтоб оттуда использовать пустую функцию везде, где необходимо

Ещё можно просто возвращать void 0: `const noop = () => void 0;`

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/features/profile-avatar/ui/ProfileAvatar.tsx
> +  onOpenModal: () => void;
> У Avatar - onClick может принимать undefined, так что если исправить тут, то в тестах не нужно использовать noop

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/features/profile-uploader-avatar-popup/ui/ProfileUploadAvatarPopup.tsx
> +const StyleModal = {
Нужно вынести это в файл styles.scss и использовать класс через 

> import { cn } from '@@shared/lib/bem';

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/pages/registration/ui/Page.tsx
> +// НАРУШЕНО НАПРАВЛЕНИЕ ЗАВИСИМОСТЕЙ!
Это исправлено в мейне

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/shared/lib/hooks/useContolledPopup.ts
> +  const [popup, setPopout] = useState<ReactNode>(null);
Кажется опечатка: setPopup

2023-07-12 09:30 UTC, N1KN commented on packages/client/src/shared/lib/model/hooks.ts
> +      // @ts-expect-error
Тоже нужны пояснения по обходу правил ТС

2023-07-18 21:02 UTC, Dveyn approved these changes
По моим знаниям, все хорошо

2023-07-18 21:41 UTC, N1KN approved these changes
Ну, будем считать, что всё норм, хотя ты и не оставил коментарии к коду :(

2023-07-18 21:41 UTC, merged